# fly.toml app configuration file generated for elonbot on 2023-10-13T11:46:33-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "elonbot"
primary_region = "lax"

[build]
